"use client";

import { createContext, useContext, useEffect, useState, useCallback, ReactNode } from "react";

type LangCode = "en" | "mr" | "bn" | "hi" | "te";

interface LanguageContextType {
  lang: LangCode;
  setLang: (l: LangCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LANGUAGES: { code: LangCode; label: string; nativeLabel: string }[] = [
  { code: "en", label: "English", nativeLabel: "English" },
  { code: "mr", label: "Marathi", nativeLabel: "मराठी" },
  { code: "bn", label: "Bengali", nativeLabel: "বাংলা" },
  { code: "hi", label: "Hindi", nativeLabel: "हिन्दी" },
  { code: "te", label: "Telugu", nativeLabel: "తెలుగు" },
];

const translations: Record<LangCode, Record<string, string>> = {
  en: {
    "nav.home": "Home", "nav.about": "About Us", "nav.services": "Services", "nav.register": "Register", "nav.profile": "My Profile", "nav.help": "Help & Support",
    "nav.login": "Login", "nav.book": "Book a Service", "nav.settings": "Settings", "nav.darkMode": "Dark Mode", "nav.language": "Language",
    "hero.badge": "The Future of Cooperative Services",
    "hero.title1": "Verified Workers.", "hero.title2": "Fair Wages. Quality Service.",
    "hero.desc": "GharPe connects you with cooperative-verified professionals — electricians, plumbers, carpenters, caregivers, and more. Every worker is insured, skilled, and fairly compensated through India's Labour Cooperative Federations.",
    "hero.cta1": "Book a Service", "hero.cta2": "Join as a Worker",
    "hero.trust1": "Multi-Level Verified", "hero.trust2": "Insurance-Backed", "hero.trust3": "Fair Wage Guaranteed",
    "marquee.verifiedWorkers": "Verified Cooperative Workers", "marquee.fairWages": "Fair Wages Guaranteed",
    "marquee.insurance": "Insurance-Backed Services", "marquee.trust": "Community Trust",
    "marquee.pricing": "Transparent Pricing", "marquee.emergency": "24/7 Emergency Support",
    "marquee.owned": "Cooperative Owned", "marquee.trained": "Professionally Trained",
    "marquee.idVerified": "ID Verified", "marquee.background": "Background Checked",
    "stats.workers": "Verified Workers", "stats.societies": "Cooperative Societies",
    "stats.services": "Services Completed", "stats.rating": "Average Rating",
    "categories.badge": "Services", "categories.title": "Popular Service Categories",
    "categories.desc": "Browse verified professionals across a wide range of household and institutional services",
    "cat.electrician": "Electrician", "cat.plumber": "Plumber", "cat.carpenter": "Carpenter",
    "cat.painter": "Painter", "cat.domestic": "Domestic Help", "cat.caregiver": "Caregiver",
    "cat.driver": "Driver", "cat.gardener": "Gardener", "cat.cleaner": "Cleaner", "cat.technician": "Technician",
    "why.badge": "Why GharPe", "why.title": "Not Just Another Gig App",
    "why.desc": "A cooperative platform built on trust, fairness, and community — where every worker is a stakeholder, not just a contractor.",
    "why.verification.title": "Multi-Level Verification", "why.verification.desc": "Every worker is verified through their cooperative federation — ID check, skill assessment, and background verification.",
    "why.wages.title": "Fair Wages for Workers", "why.wages.desc": "Our cooperative model ensures workers earn significantly more than typical gig platform rates. No exploitation.",
    "why.insurance.title": "Insurance-Backed Workers", "why.insurance.desc": "All registered workers are covered under cooperative insurance and welfare schemes at no extra cost.",
    "why.pricing.title": "Transparent Pricing", "why.pricing.desc": "No hidden charges. See estimated costs before booking with rates set cooperatively for fairness.",
    "why.local.title": "Local Cooperative Presence", "why.local.desc": "Workers are from your local area, vetted by cooperative societies you can trust and know.",
    "why.community.title": "Community-Driven", "why.community.desc": "Built by the cooperative movement, for the cooperative movement. Every decision prioritizes worker and customer welfare.",
    "how.badge": "Process", "how.title": "How It Works", "how.desc": "Simple, transparent, and trustworthy — in four easy steps",
    "how.search": "Search", "how.search.desc": "Find the service you need from our verified worker directory. Filter by skill, location, and rating.",
    "how.book": "Book", "how.book.desc": "Choose your preferred date, time, and describe the job. Get upfront pricing before confirming.",
    "how.worker": "Worker Arrives", "how.worker.desc": "A cooperative-verified professional arrives at your doorstep, insured and equipped.",
    "how.pay": "Pay & Rate", "how.pay.desc": "Pay securely through UPI, card, or cash. Rate the service to help the community.",
    "who.badge": "For Everyone", "who.title": "Who We Serve",
    "who.desc": "Whether you're a household, an institution, or a skilled worker — GharPe is built for you.",
    "who.households": "Households", "who.households.desc": "From minor repairs to deep cleaning, find trusted cooperative workers for every home need.",
    "who.institutions": "Institutions", "who.institutions.desc": "Offices, schools, hospitals — bulk service contracts with cooperative societies for ongoing maintenance.",
    "who.elderly": "Elderly & Patients", "who.elderly.desc": "Compassionate caregivers and patient support workers from verified cooperative backgrounds.",
    "who.workers": "Cooperative Workers", "who.workers.desc": "Join the digital economy while retaining cooperative benefits — insurance, fair wages, and dignity.",
    "impact.badge": "Impact", "impact.title": "Numbers That Matter", "impact.desc": "Real impact on real lives through the cooperative model",
    "coop.badge": "Cooperative Model", "coop.title": "How the Cooperative Chain Works",
    "coop.desc": "A structured, accountable system — not a loose collection of anonymous freelancers",
    "coop.federations": "Federations", "coop.federations.desc": "Set standards and welfare policies",
    "coop.societies": "Societies", "coop.societies.desc": "Recruit and manage local workers",
    "coop.verified": "Verified Workers", "coop.verified.desc": "Multi-level verified professionals",
    "coop.you": "You", "coop.you.desc": "Book with confidence",
    "testimonials.badge": "Testimonials", "testimonials.title": "What Our Community Says",
    "testimonials.desc": "Real stories from workers and customers in the cooperative network",
    "emergency.title": "Need Urgent Help?", "emergency.desc": "Book an on-demand emergency service. Verified workers available 24/7.",
    "emergency.cta": "Book Emergency Service",
    "cta.title": "Ready to Get Started?", "cta.desc": "Whether you need a skilled professional or want to join our cooperative network, GharPe is here for you.",
    "cta.noSignup": "No signup fees", "cta.cancel": "Cancel anytime", "cta.support": "24/7 support",
    "footer.desc": "A cooperative-owned marketplace connecting verified skilled workers from Labour Cooperative Federations with households and institutions.",
    "footer.quickLinks": "Quick Links", "footer.contact": "Contact Us",
    "footer.tollFree": "Toll Free, 9 AM – 8 PM", "footer.response": "Response within 24 hours",
    "footer.address": "GharPe Headquarters", "footer.city": "Kolkata, West Bengal",
    "footer.newsletter": "Stay Connected", "footer.newsletterDesc": "Get updates about new services and cooperative news.",
    "footer.emailPlaceholder": "Your email", "footer.subscribe": "Subscribe",
    "footer.toggleHint": "Toggle dark mode from the settings icon in the navbar",
    "footer.privacy": "Privacy Policy", "footer.terms": "Terms of Service", "footer.bylaws": "Cooperative Bylaws",
    "services.title": "Find a Verified Worker", "services.desc": "Browse cooperative-verified professionals for all your household and institutional needs.",
    "services.searchPlaceholder": "Search by service, name, or location...",
    "services.emergencyOnly": "Emergency Only", "services.emergencyMode": "Emergency Mode ON",
    "services.clear": "Clear", "services.workersFound": "workers found",
    "services.noResults": "No workers found", "services.noResultsDesc": "Try adjusting your filters or search terms",
    "services.bookNow": "Book Now", "services.viewProfile": "View Profile", "services.verified": "Verified",
    "services.starting": "starting", "services.back": "Back to results",
    "services.about": "About", "services.skills": "Skills", "services.certifications": "Certifications",
    "services.availability": "Availability", "services.reviews": "Recent Reviews",
    "booking.title": "Book", "booking.date": "Date", "booking.time": "Time Slot",
    "booking.selectTime": "Select time", "booking.address": "Service Address",
    "booking.addressPlaceholder": "Enter the service address", "booking.description": "Service Description",
    "booking.descPlaceholder": "Describe the work you need done...",
    "booking.fee": "Service fee", "booking.platformFee": "Platform fee", "booking.total": "Total",
    "booking.payment": "Payment Method", "booking.confirm": "Confirm Booking",
    "booking.confirmed": "Booking Confirmed!", "booking.confirmedMsg": "will contact you shortly.",
    "booking.done": "Done", "booking.processing": "Processing your booking...",
    "register.title": "Join", "register.desc": "Register as a customer, a worker, or onboard your cooperative society",
    "register.customer": "Register as Customer", "register.worker": "Register as Worker", "register.society": "Cooperative Society",
    "register.fullName": "Full Name", "register.phone": "Phone Number", "register.email": "Email",
    "register.address": "Address", "register.useLocation": "Use my current location",
    "register.language": "Preferred Language", "register.password": "Password", "register.confirmPassword": "Confirm Password",
    "register.terms": "I agree to the", "register.termsLink": "Terms", "register.privacyLink": "Privacy Policy",
    "register.createAccount": "Create Account", "register.personalDetails": "Personal Details",
    "register.coopAffiliation": "Cooperative Affiliation", "register.selectCoop": "Select your cooperative",
    "register.membershipId": "Cooperative Membership ID", "register.skillProfiling": "Skill Profiling",
    "register.serviceCategories": "Service Categories", "register.yearsExp": "Years of Experience",
    "register.certUpload": "Upload certificates", "register.serviceArea": "Service Area & Availability",
    "register.availableDays": "Available Days", "register.paymentDetails": "Payment Details",
    "register.bankName": "Bank Name", "register.ifsc": "IFSC Code", "register.accountNumber": "Account Number",
    "register.insurance": "Opt-in to Cooperative Insurance & Welfare Scheme",
    "register.insuranceDesc": "Get accident insurance, health coverage — at no extra cost.",
    "register.submitApp": "Submit Application", "register.societyName": "Society / Federation Name",
    "register.regNumber": "Registration Number", "register.region": "Region",
    "register.contactPerson": "Contact Person", "register.memberCount": "Number of Member Workers",
    "register.registerSociety": "Register Society",
    "register.success.customer": "Account Created!", "register.success.customerDesc": "Welcome to GharPe. Browse services and book verified workers.",
    "register.success.worker": "Application Submitted!", "register.success.workerDesc": "Your application is under verification. Our team will review within 3–5 business days.",
    "register.success.society": "Society Registration Received!", "register.success.societyDesc": "We'll verify your cooperative's details within 5–7 business days.",
    "help.title": "Help", "help.title2": "& Support", "help.desc": "Find answers to common questions or reach out to our support team",
    "help.emergency": "Emergency Contact", "help.emergencyDesc": "For urgent safety issues, call our 24/7 emergency helpline immediately.",
    "help.callEmergency": "Call 1800-123-4567", "help.contactTitle": "Contact Options",
    "help.callSupport": "Call Support", "help.callSupportDesc": "Mon–Sat, 9 AM – 8 PM",
    "help.emailSupport": "Email Support", "help.emailSupportDesc": "Response within 24 hours",
    "help.liveChat": "Live Chat", "help.liveChatDesc": "Chat with our support team", "help.startChat": "Start Chat",
    "help.complaint": "Raise a Complaint", "help.complaintDesc": "Report issues with bookings", "help.fileComplaint": "File Complaint",
    "help.faqTitle": "Frequently Asked Questions", "help.noResults": "No results found",
    "help.noResultsDesc": "Try a different search term", "help.searchPlaceholder": "Search frequently asked questions...",
    "help.welfareTitle": "Worker Welfare & Insurance", "help.welfareDesc": "Every worker on GharPe is covered under the cooperative's welfare scheme.",
    "help.learnMore": "Learn More", "help.chatTitle": "GharPe Support", "help.chatPlaceholder": "Type your message...",
    "about.title": "About GharPe", "about.desc": "A cooperative-owned platform redefining how skilled workers connect with the people who need them.",
    "about.mission": "Our Mission", "about.missionDesc": "To create a fair, transparent, and dignified marketplace for skilled cooperative workers.",
    "about.vision": "Our Vision", "about.visionDesc": "A future where skilled workers are empowered through cooperative ownership.",
    "about.storyBadge": "Our Story", "about.storyTitle": "From Cooperative Roots to Digital Future",
    "about.model": "How the Cooperative Model Works", "about.modelDesc": "A structured, accountable system",
    "about.impact": "Our Impact", "about.impactDesc": "Numbers that reflect our commitment to the cooperative community",
    "about.leadership": "Meet the Federation", "about.leadershipDesc": "The leadership team behind GharPe's cooperative mission",
    "about.partners": "Partner Cooperative Societies", "about.partnersDesc": "Federations and societies that power the GharPe network",
    "about.joinCta": "Want Your Cooperative Society to Join?", "about.joinCtaDesc": "Register your Labour Cooperative Federation or Society on GharPe.",
    "about.joinBtn": "Register Your Society",
    "elev.elderlyCare": "Elderly Care", "elev.patientHandling": "Patient Handling", "elev.physiotherapy": "Physiotherapy Support",
  },

  hi: {
    "nav.home": "होम", "nav.about": "हमारे बारे में", "nav.services": "सेवाएँ", "nav.register": "रजिस्टर", "nav.profile": "मेरी प्रोफ़ाइल", "nav.help": "सहायता",
    "nav.login": "लॉगिन", "nav.book": "सेवा बुक करें", "nav.settings": "सेटिंग्स", "nav.darkMode": "डार्क मोड", "nav.language": "भाषा",
    "hero.badge": "सहकारी सेवाओं का भविष्य",
    "hero.title1": "सत्यापित कामगार।", "hero.title2": "उचित वेतन। गुणवत्तापूर्ण सेवा।",
    "hero.desc": "GharPe आपको सहकारी-सत्यापित पेशेवरों से जोड़ता है — इलेक्ट्रीशियन, प्लंबर, बढ़ई, देखभालकर्ता और बहुत कुछ।",
    "hero.cta1": "सेवा बुक करें", "hero.cta2": "कामगार के रूप में जुड़ें",
    "hero.trust1": "बहु-स्तरीय सत्यापन", "hero.trust2": "बीमा-समर्थित", "hero.trust3": "उचित वेतन की गारंटी",
    "marquee.verifiedWorkers": "सत्यापित सहकारी कामगार", "marquee.fairWages": "उचित वेतन की गारंटी",
    "marquee.insurance": "बीमा-समर्थित सेवाएँ", "marquee.trust": "सामुदायिक विश्वास",
    "marquee.pricing": "पारदर्शी मूल्य निर्धारण", "marquee.emergency": "24/7 आपातकालीन सहायता",
    "marquee.owned": "सहकारी स्वामित्व", "marquee.trained": "पेशेवर प्रशिक्षित",
    "marquee.idVerified": "आईडी सत्यापित", "marquee.background": "पृष्ठभूमि जांच",
    "stats.workers": "सत्यापित कामगार", "stats.societies": "सहकारी समितियाँ",
    "stats.services": "सेवाएँ पूर्ण", "stats.rating": "औसत रेटिंग",
    "categories.badge": "सेवाएँ", "categories.title": "लोकप्रिय सेवा श्रेणियाँ",
    "categories.desc": "घरेलू और संस्थागत सेवाओं में सत्यापित पेशेवरों को ब्राउज़ करें",
    "cat.electrician": "इलेक्ट्रीशियन", "cat.plumber": "प्लंबर", "cat.carpenter": "बढ़ई",
    "cat.painter": "पेंटर", "cat.domestic": "घरेलू सहायक", "cat.caregiver": "देखभालकर्ता",
    "cat.driver": "ड्राइवर", "cat.gardener": "माली", "cat.cleaner": "सफाईकर्मी", "cat.technician": "तकनीशियन",
    "why.badge": "GharPe क्यों", "why.title": "सिर्फ एक गिग ऐप नहीं",
    "why.desc": "विश्वास, निष्पक्षता और समुदाय पर बना एक सहकारी मंच।",
    "why.verification.title": "बहु-स्तरीय सत्यापन", "why.verification.desc": "हर कामगार को उनके सहकारी महासंघ द्वारा सत्यापित किया जाता है।",
    "why.wages.title": "कामगारों के लिए उचित वेतन", "why.wages.desc": "हमारा सहकारी मॉडल सुनिश्चित करता है कि कामगारों को अधिक वेतन मिले।",
    "why.insurance.title": "बीमा-समर्थित कामगार", "why.insurance.desc": "सभी पंजीकृत कामगार सहकारी बीमा और कल्याण योजनाओं के अंतर्गत हैं।",
    "why.pricing.title": "पारदर्शी मूल्य", "why.pricing.desc": "कोई छिपे शुल्क नहीं। बुकिंग से पहले अनुमानित लागत देखें।",
    "why.local.title": "स्थानीय सहकारी उपस्थिति", "why.local.desc": "कामगार आपके स्थानीय क्षेत्र के हैं।",
    "why.community.title": "समुदाय-संचालित", "why.community.desc": "सहकारी आंदोलन द्वारा, सहकारी आंदोलन के लिए निर्मित।",
    "how.badge": "प्रक्रिया", "how.title": "यह कैसे काम करता है", "how.desc": "चार आसान कदमों में सरल और पारदर्शी",
    "how.search": "खोजें", "how.search.desc": "हमारी सत्यापित कामगार निर्देशिका में सेवा खोजें।",
    "how.book": "बुक करें", "how.book.desc": "तिथि, समय चुनें और कार्य का वर्णन करें।",
    "how.worker": "कामगार आता है", "how.worker.desc": "एक सहकारी-सत्यापित पेशेवर आपके दरवाजे पर आता है।",
    "how.pay": "भुगतान और रेट", "how.pay.desc": "UPI, कार्ड या नकद में सुरक्षित भुगतान करें।",
    "who.badge": "सभी के लिए", "who.title": "हम किसकी सेवा करते हैं",
    "who.desc": "चाहे आप घर हों, संस्था हों या कुशल कामगार — GharPe आपके लिए है।",
    "who.households": "घरेलू", "who.households.desc": "मरम्मत से लेकर गहरी सफाई तक, हर घर की जरूरत के लिए।",
    "who.institutions": "संस्थाएँ", "who.institutions.desc": "कार्यालय, स्कूल, अस्पताल — सहकारी समितियों के साथ अनुबंध।",
    "who.elderly": "बुजुर्ग और रोगी", "who.elderly.desc": "सत्यापित सहकारी पृष्ठभूमि से देखभालकर्ता।",
    "who.workers": "सहकारी कामगार", "who.workers.desc": "सहकारी लाभ बरकरार रखते हुए डिजिटल अर्थव्यवस्था में शामिल हों।",
    "impact.badge": "प्रभाव", "impact.title": "महत्वपूर्ण संख्या", "impact.desc": "सहकारी मॉडल के माध्यम से वास्तविक जीवन पर वास्तविक प्रभाव",
    "coop.badge": "सहकारी मॉडल", "coop.title": "सहकारी श्रृंखला कैसे काम करती है",
    "coop.desc": "एक संरचित, जवाबदेह प्रणाली",
    "coop.federations": "महासंघ", "coop.federations.desc": "मानक और कल्याण नीतियाँ निर्धारित करते हैं",
    "coop.societies": "समितियाँ", "coop.societies.desc": "स्थानीय कामगारों की भर्ती और प्रबंधन",
    "coop.verified": "सत्यापित कामगार", "coop.verified.desc": "बहु-स्तरीय सत्यापित पेशेवर",
    "coop.you": "आप", "coop.you.desc": "आत्मविश्वास से बुक करें",
    "testimonials.badge": "प्रशंसापत्र", "testimonials.title": "हमारा समुदाय क्या कहता है",
    "testimonials.desc": "सहकारी नेटवर्क में कामगारों और ग्राहकों की वास्तविक कहानियाँ",
    "emergency.title": "तत्काल सहायता चाहिए?", "emergency.desc": "ऑन-डिमांड आपातकालीन सेवा बुक करें।",
    "emergency.cta": "आपातकालीन सेवा बुक करें",
    "cta.title": "शुरू करने के लिए तैयार?", "cta.desc": "GharPe आपके लिए यहाँ है।",
    "cta.noSignup": "कोई साइनअप शुल्क नहीं", "cta.cancel": "कभी भी रद्द करें", "cta.support": "24/7 सहायता",
    "footer.desc": "सहकारी-स्वामित्व वाला बाज़ार जो सत्यापित कुशल कामगारों को घरों और संस्थाओं से जोड़ता है।",
    "footer.quickLinks": "त्वरित लिंक", "footer.contact": "संपर्क करें",
    "footer.tollFree": "टोल फ्री, सुबह 9 – रात 8", "footer.response": "24 घंटे के भीतर प्रतिक्रिया",
    "footer.address": "घरपे मुख्यालय", "footer.city": "कोलकाता, पश्चिम बंगाल",
    "footer.newsletter": "जुड़े रहें", "footer.newsletterDesc": "नई सेवाओं और सहकारी समाचारों के अपडेट प्राप्त करें।",
    "footer.emailPlaceholder": "आपका ईमेल", "footer.subscribe": "सदस्यता लें",
    "footer.toggleHint": "नेवबार में सेटिंग्स आइकन से डार्क मोड टॉगल करें",
    "footer.privacy": "गोपनीयता नीति", "footer.terms": "सेवा की शर्तें", "footer.bylaws": "सहकारी नियमावली",
    "services.title": "सत्यापित कामगार खोजें", "services.desc": "अपनी सभी घरेलू और संस्थागत जरूरतों के लिए।",
    "services.searchPlaceholder": "सेवा, नाम या स्थान से खोजें...",
    "services.emergencyOnly": "केवल आपातकाल", "services.emergencyMode": "आपातकाल मोड चालू",
    "services.clear": "साफ करें", "services.workersFound": "कामगार मिले",
    "services.noResults": "कोई कामगार नहीं मिला", "services.noResultsDesc": "अपने फ़िल्टर बदलकर देखें",
    "services.bookNow": "अभी बुक करें", "services.viewProfile": "प्रोफ़ाइल देखें", "services.verified": "सत्यापित",
    "services.starting": "शुरू", "services.back": "परिणामों पर वापस",
    "services.about": "के बारे में", "services.skills": "कौशल", "services.certifications": "प्रमाणपत्र",
    "services.availability": "उपलब्धता", "services.reviews": "हालिया समीक्षाएँ",
    "booking.title": "बुक करें", "booking.date": "तिथि", "booking.time": "समय स्लॉट",
    "booking.selectTime": "समय चुनें", "booking.address": "सेवा पता",
    "booking.addressPlaceholder": "सेवा का पता दर्ज करें", "booking.description": "सेवा विवरण",
    "booking.descPlaceholder": "आपको क्या कार्य चाहिए...",
    "booking.fee": "सेवा शुल्क", "booking.platformFee": "प्लेटफ़ॉर्म शुल्क", "booking.total": "कुल",
    "booking.payment": "भुगतान विधि", "booking.confirm": "बुकिंग की पुष्टि करें",
    "booking.confirmed": "बुकिंग पुष्ट!", "booking.confirmedMsg": "शीघ्र ही आपसे संपर्क करेंगे।",
    "booking.done": "हो गया", "booking.processing": "बुकिंग प्रसंस्करण...",
    "register.title": "जुड़ें", "register.desc": "ग्राहक, कामगार या सहकारी समिति के रूप में रजिस्टर करें",
    "register.customer": "ग्राहक रजिस्टर", "register.worker": "कामगार रजिस्टर", "register.society": "सहकारी समिति",
    "register.fullName": "पूरा नाम", "register.phone": "फ़ोन नंबर", "register.email": "ईमेल",
    "register.address": "पता", "register.useLocation": "मेरा वर्तमान स्थान उपयोग करें",
    "register.language": "पसंदीदा भाषा", "register.password": "पासवर्ड", "register.confirmPassword": "पासवर्ड की पुष्टि",
    "register.terms": "मैं सहमत हूँ", "register.termsLink": "शर्तें", "register.privacyLink": "गोपनीयता नीति",
    "register.createAccount": "खाता बनाएं", "register.personalDetails": "व्यक्तिगत विवरण",
    "register.coopAffiliation": "सहकारी संबद्धता", "register.selectCoop": "अपनी सहकारी समिति चुनें",
    "register.membershipId": "सहकारी सदस्यता आईडी", "register.skillProfiling": "कौशल प्रोफ़ाइलिंग",
    "register.serviceCategories": "सेवा श्रेणियाँ", "register.yearsExp": "अनुभव के वर्ष",
    "register.certUpload": "प्रमाणपत्र अपलोड करें", "register.serviceArea": "सेवा क्षेत्र और उपलब्धता",
    "register.availableDays": "उपलब्ध दिन", "register.paymentDetails": "भुगतान विवरण",
    "register.bankName": "बैंक का नाम", "register.ifsc": "IFSC कोड", "register.accountNumber": "खाता संख्या",
    "register.insurance": "सहकारी बीमा और कल्याण योजना में शामिल हों",
    "register.insuranceDesc": "दुर्घटना बीमा, स्वास्थ्य कवरेज — बिना किसी अतिरिक्त लागत के।",
    "register.submitApp": "आवेदन जमा करें", "register.societyName": "समिति / महासंघ का नाम",
    "register.regNumber": "पंजीकरण संख्या", "register.region": "क्षेत्र",
    "register.contactPerson": "संपर्क व्यक्ति", "register.memberCount": "सदस्य कामगारों की संख्या",
    "register.registerSociety": "समिति रजिस्टर करें",
    "register.success.customer": "खाता बना!", "register.success.customerDesc": "GharPe में आपका स्वागत है।",
    "register.success.worker": "आवेदन जमा हुआ!", "register.success.workerDesc": "आपका आवेदन सत्यापन के अधीन है।",
    "register.success.society": "समिति पंजीकरण प्राप्त!", "register.success.societyDesc": "हम 5–7 कार्य दिवसों में विवरण सत्यापित करेंगे।",
    "help.title": "सहायता", "help.title2": "और समर्थन", "help.desc": "सामान्य प्रश्नों के उत्तर खोजें या हमसे संपर्क करें",
    "help.emergency": "आपातकालीन संपर्क", "help.emergencyDesc": "तत्काल सुरक्षा मुद्दों के लिए, तुरंत कॉल करें।",
    "help.callEmergency": "कॉल करें 1800-123-4567", "help.contactTitle": "संपर्क विकल्प",
    "help.callSupport": "कॉल सहायता", "help.callSupportDesc": "सोम-शनि, सुबह 9 – रात 8",
    "help.emailSupport": "ईमेल सहायता", "help.emailSupportDesc": "24 घंटे में प्रतिक्रिया",
    "help.liveChat": "लाइव चैट", "help.liveChatDesc": "हमारी टीम से चैट करें", "help.startChat": "चैट शुरू करें",
    "help.complaint": "शिकायत दर्ज करें", "help.complaintDesc": "बुकिंग की समस्याएँ रिपोर्ट करें", "help.fileComplaint": "शिकायत दर्ज",
    "help.faqTitle": "अक्सर पूछे जाने वाले प्रश्न", "help.noResults": "कोई परिणाम नहीं",
    "help.noResultsDesc": "अलग खोज शब्द आज़माएँ", "help.searchPlaceholder": "अक्सर पूछे जाने वाले प्रश्न खोजें...",
    "help.welfareTitle": "कामगार कल्याण और बीमा", "help.welfareDesc": "GharPe का हर कामगार सहकारी कल्याण योजना के अंतर्गत है।",
    "help.learnMore": "और जानें", "help.chatTitle": "GharPe सहायता", "help.chatPlaceholder": "अपना संदेश लिखें...",
    "about.title": "GharPe के बारे में", "about.desc": "एक सहकारी-स्वामित्व वाला मंच।",
    "about.mission": "हमारा मिशन", "about.missionDesc": "कुशल सहकारी कामगारों के लिए एक उचित और गरिमामय बाज़ार बनाना।",
    "about.vision": "हमारी दृष्टि", "about.visionDesc": "एक ऐसा भविष्य जहाँ कुशल कामगार सहकारी स्वामित्व से सशक्त हों।",
    "about.storyBadge": "हमारी कहानी", "about.storyTitle": "सहकारी जड़ों से डिजिटल भविष्य तक",
    "about.model": "सहकारी मॉडल कैसे काम करता है", "about.modelDesc": "एक संरचित, जवाबदेह प्रणाली",
    "about.impact": "हमारा प्रभाव", "about.impactDesc": "सहकारी समुदाय के प्रति हमारी प्रतिबद्धता",
    "about.leadership": "महासंघ से मिलें", "about.leadershipDesc": "GharPe के सहकारी मिशन के पीछे नेतृत्व टीम",
    "about.partners": "साझेदार सहकारी समितियाँ", "about.partnersDesc": "GharPe नेटवर्क को शक्ति देने वाले महासंघ और समितियाँ",
    "about.joinCta": "आपकी सहकारी समिति जुड़ना चाहती है?", "about.joinCtaDesc": "GharPe पर अपनी सहकारी समिति पंजीकृत करें।",
    "about.joinBtn": "अपनी समिति रजिस्टर करें",
    "elev.elderlyCare": "बुजुर्ग देखभाल", "elev.patientHandling": "रोगी देखभाल", "elev.physiotherapy": "फिजियोथेरेपी सहायता",
  },

  bn: {
    "nav.home": "হোম", "nav.about": "আমাদের সম্পর্কে", "nav.services": "সেবাসমূহ", "nav.register": "নিবন্ধন", "nav.profile": "আমার প্রোফাইল", "nav.help": "সহায়তা",
    "nav.login": "লগইন", "nav.book": "সেবা বুক করুন", "nav.settings": "সেটিংস", "nav.darkMode": "ডার্ক মোড", "nav.language": "ভাষা",
    "hero.badge": "সমবায় সেবার ভবিষ্যৎ",
    "hero.title1": "যাচাইকৃত শ্রমিক।", "hero.title2": "ন্যায্য বেতন। মানসম্মত সেবা।",
    "hero.desc": "GharPe আপনাকে সমবায়-যাচাইকৃত পেশাদারদের সাথে সংযুক্ত করে।",
    "hero.cta1": "সেবা বুক করুন", "hero.cta2": "শ্রমিক হিসাবে যোগ দিন",
    "hero.trust1": "বহু-স্তরীয় যাচাই", "hero.trust2": "বীমা-সমর্থিত", "hero.trust3": "ন্যায্য বেতন নিশ্চিত",
    "marquee.verifiedWorkers": "যাচাইকৃত সমবায় শ্রমিক", "marquee.fairWages": "ন্যায্য বেতন নিশ্চিত",
    "marquee.insurance": "বীমা-সমর্থিত সেবা", "marquee.trust": "সম্প্রদায়ের বিশ্বাস",
    "marquee.pricing": "স্বচ্ছ মূল্য নির্ধারণ", "marquee.emergency": "২৪/৭ জরুরি সহায়তা",
    "marquee.owned": "সমবায় মালিকানা", "marquee.trained": "পেশাদার প্রশিক্ষিত",
    "marquee.idVerified": "আইডি যাচাইকৃত", "marquee.background": "পটভূমি যাচাই",
    "stats.workers": "যাচাইকৃত শ্রমিক", "stats.societies": "সমবায় সমিতি",
    "stats.services": "সম্পন্ন সেবা", "stats.rating": "গড় রেটিং",
    "categories.badge": "সেবাসমূহ", "categories.title": "জনপ্রিয় সেবা বিভাগ",
    "categories.desc": "গৃহস্থালি ও প্রাতিষ্ঠানিক সেবায় যাচাইকৃত পেশাদার খুঁজুন",
    "cat.electrician": "ইলেকট্রিশিয়ান", "cat.plumber": "প্লাম্বার", "cat.carpenter": "কারপেন্টার",
    "cat.painter": "পেইন্টার", "cat.domestic": "গৃহসেবিকা", "cat.caregiver": "যত্নকারী",
    "cat.driver": "চালক", "cat.gardener": "বাগানিয়া", "cat.cleaner": "পরিষ্কারক", "cat.technician": "প্রযুক্তিবিদ",
    "why.badge": "কেন GharPe", "why.title": "শুধু আরেকটি গিগ অ্যাপ নয়",
    "why.desc": "বিশ্বাস, ন্যায়বিচার এবং সম্প্রদায়ের উপর নির্মিত একটি সমবায় প্ল্যাটফর্ম।",
    "why.verification.title": "বহু-স্তরীয় যাচাই", "why.verification.desc": "প্রতিটি শ্রমিক সমবায় ফেডারেশন দ্বারা যাচাইকৃত।",
    "why.wages.title": "ন্যায্য বেতন", "why.wages.desc": "সমবায় মডেলে শ্রমিকরা বেশি পারিশ্রমিক পান।",
    "why.insurance.title": "বীমা-সমর্থিত শ্রমিক", "why.insurance.desc": "সমস্ত নিবন্ধিত শ্রমিক সমবায় বীমায় অন্তর্ভুক্ত।",
    "why.pricing.title": "স্বচ্ছ মূল্য", "why.pricing.desc": "কোনো লুকানো চার্জ নেই।",
    "why.local.title": "স্থানীয় সমবায়", "why.local.desc": "শ্রমিকরা আপনার এলাকার।",
    "why.community.title": "সম্প্রদায়-চালিত", "why.community.desc": "সমবায় আন্দোলন দ্বারা নির্মিত।",
    "how.badge": "প্রক্রিয়া", "how.title": "কীভাবে কাজ করে", "how.desc": "চারটি সহজ ধাপে সরল ও স্বচ্ছ",
    "how.search": "অনুসন্ধান", "how.search.desc": "সত্যাপিত শ্রমিক তালিকায় সেবা খুঁজুন।",
    "how.book": "বুক", "how.book.desc": "তারিখ, সময় বেছে নিন।",
    "how.worker": "শ্রমিক আসে", "how.worker.desc": "সমবায়-যাচাইকৃত পেশাদার আসে।",
    "how.pay": "পেমেন্ট", "how.pay.desc": "UPI, কার্ড বা নগদে পেমেন্ট।",
    "who.badge": "সকলের জন্য", "who.title": "আমরা কাকে সেবা দিই",
    "who.desc": "গৃহস্থালি, প্রতিষ্ঠান বা দক্ষ শ্রমিক — GharPe আপনার জন্য।",
    "who.households": "গৃহস্থালি", "who.households.desc": "মেরামত থেকে গভীর পরিষ্কার পর্যন্ত।",
    "who.institutions": "প্রতিষ্ঠান", "who.institutions.desc": "অফিস, স্কুল, হাসপাতাল।",
    "who.elderly": "বয়স্ক ও রোগী", "who.elderly.desc": "যাচাইকৃত পটভূমি থেকে যত্নকারী।",
    "who.workers": "সমবায় শ্রমিক", "who.workers.desc": "সমবায় সুবিধা বজায় রেখে ডিজিটাল অর্থনীতিতে যোগ দিন।",
    "impact.badge": "প্রভাব", "impact.title": "গুরুত্বপূর্ণ সংখ্যা", "impact.desc": "সমবায় মডেলের মাধ্যমে প্রকৃত প্রভাব",
    "coop.badge": "সমবায় মডেল", "coop.title": "সমবায় শৃঙ্খল কীভাবে কাজ করে", "coop.desc": "সংগঠিত, জবাবদিহি সিস্টেম",
    "coop.federations": "ফেডারেশন", "coop.federations.desc": "মান ও কল্যাণ নীতি নির্ধারণ",
    "coop.societies": "সমিতি", "coop.societies.desc": "স্থানীয় শ্রমিক নিয়োগ ও পরিচালনা",
    "coop.verified": "যাচাইকৃত শ্রমিক", "coop.verified.desc": "বহু-স্তরীয় যাচাই",
    "coop.you": "আপনি", "coop.you.desc": "আত্মবিশ্বাসের সাথে বুক করুন",
    "testimonials.badge": "প্রশংসাপত্র", "testimonials.title": "সম্প্রদায়ের কথা", "testimonials.desc": "প্রকৃত গল্প",
    "emergency.title": "জরুরি সাহায্য প্রয়োজন?", "emergency.desc": "জরুরি সেবা বুক করুন।",
    "emergency.cta": "জরুরি সেবা বুক করুন",
    "cta.title": "শুরু করতে প্রস্তুত?", "cta.desc": "GharPe আপনার জন্য এখানে।",
    "cta.noSignup": "কোনো সাইনআপ ফি নেই", "cta.cancel": "যেকোনো সময় বাতিল", "cta.support": "২৪/৭ সহায়তা",
    "footer.desc": "সমবায়-মালিকানাধীন বাজার।", "footer.quickLinks": "দ্রুত লিঙ্ক", "footer.contact": "যোগাযোগ",
    "footer.tollFree": "টোল ফ্রি, সকাল ৯ – রাত ৮", "footer.response": "২৪ ঘণ্টায় প্রতিক্রিয়া",
    "footer.address": "ঘরপে সদর দপ্তর", "footer.city": "কলকাতা, পশ্চিমবঙ্গ",
    "footer.newsletter": "সংযুক্ত থাকুন", "footer.newsletterDesc": "আপডেট পান।",
    "footer.emailPlaceholder": "ইমেইল", "footer.subscribe": "সাবস্ক্রাইব",
    "footer.toggleHint": "ডার্ক মোড টগল করুন", "footer.privacy": "গোপনীয়তা নীতি",
    "footer.terms": "সেবার শর্তাবলী", "footer.bylaws": "সমবায় বিধি",
    "services.title": "যাচাইকৃত শ্রমিক খুঁজুন", "services.desc": "সকল সেবার জন্য।",
    "services.searchPlaceholder": "অনুসন্ধান...", "services.emergencyOnly": "শুধু জরুরি",
    "services.emergencyMode": "জরুরি মোড চালু", "services.clear": "পরিষ্কার",
    "services.workersFound": "শ্রমিক পাওয়া গেছে", "services.noResults": "কোনো শ্রমিক পাওয়া যায়নি",
    "services.noResultsDesc": "ফিল্টার পরিবর্তন করে দেখুন", "services.bookNow": "এখনই বুক", "services.viewProfile": "প্রোফাইল",
    "services.verified": "যাচাইকৃত", "services.starting": "শুরু", "services.back": "ফিরে যান",
    "services.skills": "দক্ষতা", "services.certifications": "সার্টিফিকেশন", "services.availability": "উপলব্ধতা", "services.reviews": "পর্যালোচনা",
    "booking.title": "বুক", "booking.date": "তারিখ", "booking.time": "সময়", "booking.selectTime": "সময় নির্বাচন",
    "booking.address": "ঠিকানা", "booking.addressPlaceholder": "ঠিকানা লিখুন",
    "booking.description": "বিবরণ", "booking.descPlaceholder": "কী কাজ দরকার...",
    "booking.fee": "সেবা ফি", "booking.platformFee": "প্ল্যাটফর্ম ফি", "booking.total": "মোট",
    "booking.payment": "পেমেন্ট", "booking.confirm": "বুকিং নিশ্চিত", "booking.confirmed": "বুকিং নিশ্চিত!",
    "booking.confirmedMsg": "শীঘ্রই যোগাযোগ করবে।", "booking.done": "হয়ে গেছে", "booking.processing": "প্রক্রিয়াকরণ...",
    "register.title": "যোগ দিন", "register.desc": "নিবন্ধন করুন",
    "register.customer": "গ্রাহক নিবন্ধন", "register.worker": "শ্রমিক নিবন্ধন", "register.society": "সমবায় সমিতি",
    "register.fullName": "পুরো নাম", "register.phone": "ফোন", "register.email": "ইমেইল",
    "register.address": "ঠিকানা", "register.useLocation": "অবস্থান ব্যবহার", "register.language": "ভাষা",
    "register.password": "পাসওয়ার্ড", "register.confirmPassword": "পাসওয়ার্ড নিশ্চিত",
    "register.terms": "সম্মত", "register.termsLink": "শর্তাবলী", "register.privacyLink": "গোপনীয়তা",
    "register.createAccount": "অ্যাকাউন্ট তৈরি", "register.personalDetails": "ব্যক্তিগত তথ্য",
    "register.coopAffiliation": "সমবায় সম্পর্ক", "register.selectCoop": "সমবায় নির্বাচন",
    "register.membershipId": "সদস্যপদ আইডি", "register.skillProfiling": "দক্ষতা প্রোফাইলিং",
    "register.serviceCategories": "সেবা বিভাগ", "register.yearsExp": "অভিজ্ঞতা",
    "register.certUpload": "সার্টিফিকেট", "register.serviceArea": "সেবা এলাকা",
    "register.availableDays": "উপলব্ধ দিন", "register.paymentDetails": "পেমেন্ট তথ্য",
    "register.bankName": "ব্যাংক", "register.ifsc": "IFSC", "register.accountNumber": "অ্যাকাউন্ট",
    "register.insurance": "বীমায় যোগ দিন", "register.insuranceDesc": "দুর্ঘটনা বীমা, স্বাস্থ্য।",
    "register.submitApp": "আবেদন জমা", "register.societyName": "সমিতির নাম",
    "register.regNumber": "নিবন্ধন নম্বর", "register.region": "অঞ্চল",
    "register.contactPerson": "যোগাযোগ ব্যক্তি", "register.memberCount": "সদস্য সংখ্যা",
    "register.registerSociety": "সমিতি নিবন্ধন",
    "register.success.customer": "অ্যাকাউন্ট!", "register.success.customerDesc": "স্বাগতম।",
    "register.success.worker": "আবেদন!", "register.success.workerDesc": "যাচাইয়ের অধীনে।",
    "register.success.society": "নিবন্ধন!", "register.success.societyDesc": "যাচাই করবো।",
    "help.title": "সহায়তা", "help.title2": "সমর্থন", "help.desc": "উত্তর খুঁজুন বা যোগাযোগ করুন",
    "help.emergency": "জরুরি যোগাযোগ", "help.emergencyDesc": "কল করুন।", "help.callEmergency": "কল ১৮০০-১২৩-৪৫৬৭",
    "help.contactTitle": "যোগাযোগ", "help.callSupport": "কল", "help.callSupportDesc": "সোম-শনি ৯-৮",
    "help.emailSupport": "ইমেইল", "help.emailSupportDesc": "২৪ ঘণ্টা", "help.liveChat": "চ্যাট", "help.liveChatDesc": "চ্যাট করুন", "help.startChat": "শুরু",
    "help.complaint": "অভিযোগ", "help.complaintDesc": "রিপোর্ট", "help.fileComplaint": "দায়ের",
    "help.faqTitle": "প্রশ্নোত্তর", "help.noResults": "নেই", "help.noResultsDesc": "অন্য শব্দ চেষ্টা",
    "help.searchPlaceholder": "অনুসন্ধান...", "help.welfareTitle": "শ্রমিক কল্যাণ", "help.welfareDesc": "সকল শ্রমিক বীমায়।",
    "help.learnMore": "আরও", "help.chatTitle": "GharPe সহায়তা", "help.chatPlaceholder": "বার্তা...",
    "about.title": "GharPe সম্পর্কে", "about.desc": "সমবায়-মালিকানাধীন প্ল্যাটফর্ম।",
    "about.mission": "মিশন", "about.missionDesc": "ন্যায্য বাজার তৈরি।",
    "about.vision": "দৃষ্টি", "about.visionDesc": "দক্ষ শ্রমিকদের ক্ষমতায়ন।",
    "about.storyBadge": "আমাদের গল্প", "about.storyTitle": "সমবায় থেকে ডিজিটাল",
    "about.model": "সমবায় মডেল", "about.modelDesc": "সংগঠিত সিস্টেম",
    "about.impact": "প্রভাব", "about.impactDesc": "প্রতিশ্রুতি",
    "about.leadership": "নেতৃত্ব", "about.leadershipDesc": "দল",
    "about.partners": "পার্টনার", "about.partnersDesc": "নেটওয়ার্ক",
    "about.joinCta": "যোগ দিতে চান?", "about.joinCtaDesc": "নিবন্ধন করুন।", "about.joinBtn": "নিবন্ধন",
    "elev.elderlyCare": "বয়স্ক", "elev.patientHandling": "রোগী", "elev.physiotherapy": "ফিজিয়ো",
  },

  mr: {
    "nav.home": "मुख्यपृष्ठ", "nav.about": "आमच्याबद्दल", "nav.services": "सेवा", "nav.register": "नोंदणी", "nav.profile": "माझे प्रोफाइल", "nav.help": "मदत",
    "nav.login": "लॉगिन", "nav.book": "सेवा बुक करा", "nav.settings": "सेटिंग्ज", "nav.darkMode": "डार्क मोड", "nav.language": "भाषा",
    "hero.badge": "सहकारी सेवांचे भविष्य",
    "hero.title1": "प्रमाणित कामगार.", "hero.title2": "योग्य वेतन. दर्जेदार सेवा.",
    "hero.desc": "GharPe तुम्हाला सहकारी-प्रमाणित व्यावसायिकांशी जोडतो.",
    "hero.cta1": "सेवा बुक करा", "hero.cta2": "कामगार म्हणून सामील व्हा",
    "hero.trust1": "बहुस्तरीय प्रमाणन", "hero.trust2": "विमा-समर्थित", "hero.trust3": "योग्य वेतन हमी",
    "marquee.verifiedWorkers": "प्रमाणित सहकारी कामगार", "marquee.fairWages": "योग्य वेतन हमी",
    "marquee.insurance": "विमा-समर्थित सेवा", "marquee.trust": "सामुदायिक विश्वास",
    "marquee.pricing": "पारदर्शक किंमत", "marquee.emergency": "24/7 आणीबाणी मदत",
    "marquee.owned": "सहकारी मालकी", "marquee.trained": "व्यावसायिक प्रशिक्षित",
    "marquee.idVerified": "ओळखपत्र प्रमाणित", "marquee.background": "पार्श्वभूमी तपासणी",
    "stats.workers": "प्रमाणित कामगार", "stats.societies": "सहकारी संस्था",
    "stats.services": "पूर्ण सेवा", "stats.rating": "सरासरी रेटिंग",
    "categories.badge": "सेवा", "categories.title": "लोकप्रिय सेवा श्रेणी",
    "categories.desc": "घरगुती आणि संस्थात्मक सेवांमधील प्रमाणित व्यावसायिक पहा",
    "cat.electrician": "इलेक्ट्रीशियन", "cat.plumber": "प्लंबर", "cat.carpenter": "बढई",
    "cat.painter": "पेंटर", "cat.domestic": "घरगुती मदत", "cat.caregiver": "काळजी घेणारा",
    "cat.driver": "चालक", "cat.gardener": "माळी", "cat.cleaner": "स्वच्छताकर्मी", "cat.technician": "तंत्रज्ञ",
    "why.badge": "GharPe का", "why.title": "फक्त एक गिग ॲप नाही",
    "why.desc": "विश्वास, न्याय आणि समुदायावर आधारित सहकारी व्यासपीठ.",
    "why.verification.title": "बहुस्तरीय प्रमाणन", "why.verification.desc": "प्रत्येक कामगार सहकारी महासंघाद्वारे प्रमाणित.",
    "why.wages.title": "कामगारांना योग्य वेतन", "why.wages.desc": "सहकारी मॉडेलमुळे अधिक पारिश्रमिक.",
    "why.insurance.title": "विमा-समर्थित कामगार", "why.insurance.desc": "सर्व कामगार विमा आणि कल्याण योजनांत.",
    "why.pricing.title": "पारदर्शक किंमत", "why.pricing.desc": "कोणतीही लपवलेली फी नाही.",
    "why.local.title": "स्थानिक सहकारी", "why.local.desc": "कामगार तुमच्या भागातील.",
    "why.community.title": "समुदाय-संचालित", "why.community.desc": "सहकारी चळवळीने निर्मित.",
    "how.badge": "प्रक्रिया", "how.title": "हे कसे काम करते", "how.desc": "चार सोप्या पायऱ्यांमध्ये",
    "how.search": "शोधा", "how.search.desc": "सत्यापित कामगार निर्देशिकेत सेवा शोधा.",
    "how.book": "बुक करा", "how.book.desc": "तारीख, वेळ निवडा.",
    "how.worker": "कामगार येतो", "how.worker.desc": "सहकारी-प्रमाणित व्यावसायिक येतो.",
    "how.pay": "पेमेंट", "how.pay.desc": "UPI, कार्ड किंवा रोख मध्ये पेमेंट.",
    "who.badge": "सर्वांसाठी", "who.title": "आम्ही कोणाला सेवा देतो",
    "who.desc": "घरगुती, संस्था किंवा कामगार — GharPe तुमच्यासाठी.",
    "who.households": "घरगुती", "who.households.desc": "दुरुस्तीपासून स्वच्छतेपर्यंत.",
    "who.institutions": "संस्था", "who.institutions.desc": "कार्यालये, शाळा, रुग्णालये.",
    "who.elderly": "ज्येष्ठ", "who.elderly.desc": "प्रमाणित काळजी घेणारे.",
    "who.workers": "सहकारी कामगार", "who.workers.desc": "सहकारी फायदे कायम ठेवता.",
    "impact.badge": "प्रभाव", "impact.title": "महत्त्वाची आकडेवारी", "impact.desc": "वास्तविक प्रभाव",
    "coop.badge": "सहकारी मॉडेल", "coop.title": "सहकारी श्रृंखला", "coop.desc": "संरचित प्रणाली",
    "coop.federations": "महासंघ", "coop.federations.desc": "मानक निर्धारित",
    "coop.societies": "समिती", "coop.societies.desc": "कामगार व्यवस्थापन",
    "coop.verified": "प्रमाणित कामगार", "coop.verified.desc": "बहुस्तरीय प्रमाणन",
    "coop.you": "तुम्ही", "coop.you.desc": "आत्मविश्वासाने बुक करा",
    "testimonials.badge": "प्रशंसापत्र", "testimonials.title": "समुदाय काय म्हणतो", "testimonials.desc": "वास्तविक कथा",
    "emergency.title": "तातडीची मदत?", "emergency.desc": "आणीबाणी सेवा बुक करा.",
    "emergency.cta": "आणीबाणी सेवा",
    "cta.title": "सुरू करायला तयार?", "cta.desc": "GharPe तुमच्यासाठी आहे.",
    "cta.noSignup": "साइनअप फी नाही", "cta.cancel": "कधीही रद्द", "cta.support": "24/7 मदत",
    "footer.desc": "सहकारी बाजारपेठ.", "footer.quickLinks": "लिंक्स", "footer.contact": "संपर्क",
    "footer.tollFree": "टोल फ्री, ९-८", "footer.response": "२४ तासांत",
    "footer.address": "घरपे मुख्यालय", "footer.city": "कोलकाता, पश्चिम बंगाल",
    "footer.newsletter": "जोडलेले रहा", "footer.newsletterDesc": "अपडेट मिळवा.",
    "footer.emailPlaceholder": "ईमेल", "footer.subscribe": "सदस्यता",
    "footer.toggleHint": "डार्क मोड टॉगल करा", "footer.privacy": "गोपनीयता",
    "footer.terms": "अटी", "footer.bylaws": "नियमावली",
    "services.title": "प्रमाणित कामगार शोधा", "services.desc": "सर्व सेवांसाठी.",
    "services.searchPlaceholder": "शोधा...", "services.emergencyOnly": "फक्त आणीबाणी",
    "services.emergencyMode": "आणीबाणी मोड", "services.clear": "साफ",
    "services.workersFound": "कामगार", "services.noResults": "नाही",
    "services.noResultsDesc": "बदला", "services.bookNow": "बुक", "services.viewProfile": "प्रोफाइल",
    "services.verified": "प्रमाणित", "services.starting": "सुरू", "services.back": "परत",
    "services.skills": "कौशल्य", "services.certifications": "प्रमाणपत्र", "services.availability": "उपलब्धता", "services.reviews": "समीक्षा",
    "booking.title": "बुक", "booking.date": "तारीख", "booking.time": "वेळ", "booking.selectTime": "वेळ निवडा",
    "booking.address": "पत्ता", "booking.addressPlaceholder": "पत्ता",
    "booking.description": "विवरण", "booking.descPlaceholder": "काय करायचं...",
    "booking.fee": "शुल्क", "booking.platformFee": "प्लॅटफॉर्म", "booking.total": "एकूण",
    "booking.payment": "पेमेंट", "booking.confirm": "पुष्टी", "booking.confirmed": "पुष्ट!",
    "booking.confirmedMsg": "संपर्क करू.", "booking.done": "झालं", "booking.processing": "प्रक्रिया...",
    "register.title": "सामील व्हा", "register.desc": "नोंदणी करा",
    "register.customer": "ग्राहक", "register.worker": "कामगार", "register.society": "संस्था",
    "register.fullName": "पूर्ण नाव", "register.phone": "फोन", "register.email": "ईमेल",
    "register.address": "पत्ता", "register.useLocation": "स्थान वापरा", "register.language": "भाषा",
    "register.password": "पासवर्ड", "register.confirmPassword": "पुष्टी",
    "register.terms": "सहमत", "register.termsLink": "अटी", "register.privacyLink": "गोपनीयता",
    "register.createAccount": "खाते तयार", "register.personalDetails": "माहिती",
    "register.coopAffiliation": "सहकारी", "register.selectCoop": "निवडा",
    "register.membershipId": "सदस्यता आयडी", "register.skillProfiling": "कौशल्य",
    "register.serviceCategories": "सेवा", "register.yearsExp": "अनुभव",
    "register.certUpload": "प्रमाणपत्र", "register.serviceArea": "क्षेत्र",
    "register.availableDays": "दिवस", "register.paymentDetails": "पेमेंट",
    "register.bankName": "बँक", "register.ifsc": "IFSC", "register.accountNumber": "खाते",
    "register.insurance": "विमा", "register.insuranceDesc": "बिना अतिरिक्त.",
    "register.submitApp": "अर्ज", "register.societyName": "नाव",
    "register.regNumber": "नोंदणी", "register.region": "प्रदेश",
    "register.contactPerson": "संपर्क", "register.memberCount": "सदस्य",
    "register.registerSociety": "नोंदणी",
    "register.success.customer": "खाते!", "register.success.customerDesc": "स्वागत.",
    "register.success.worker": "अर्ज!", "register.success.workerDesc": "तपासणी.",
    "register.success.society": "नोंदणी!", "register.success.societyDesc": "तपास.",
    "help.title": "मदत", "help.title2": "आणि समर्थन", "help.desc": "उत्तरे शोधा",
    "help.emergency": "आणीबाणी", "help.emergencyDesc": "कॉल करा.", "help.callEmergency": "१८००-१२३-४५६७",
    "help.contactTitle": "संपर्क", "help.callSupport": "कॉल", "help.callSupportDesc": "९-८",
    "help.emailSupport": "ईमेल", "help.emailSupportDesc": "२४ तास", "help.liveChat": "चॅट", "help.liveChatDesc": "चॅट करा", "help.startChat": "सुरू",
    "help.complaint": "तक्रार", "help.complaintDesc": "रिपोर्ट", "help.fileComplaint": "दाखल",
    "help.faqTitle": "प्रश्नोत्तर", "help.noResults": "नाही", "help.noResultsDesc": "बदला",
    "help.searchPlaceholder": "शोधा...", "help.welfareTitle": "कामगार कल्याण", "help.welfareDesc": "विमा-समर्थित.",
    "help.learnMore": "अधिक", "help.chatTitle": "GharPe मदत", "help.chatPlaceholder": "संदेश...",
    "about.title": "GharPe बद्दल", "about.desc": "सहकारी मंच.",
    "about.mission": "मिशन", "about.missionDesc": "योग्य बाजार.",
    "about.vision": "दृष्टी", "about.visionDesc": "कामगार सशक्तिकरण.",
    "about.storyBadge": "कथा", "about.storyTitle": "सहकारीपासून डिजिटलपर्यंत",
    "about.model": "सहकारी मॉडेल", "about.modelDesc": "संरचित प्रणाली",
    "about.impact": "प्रभाव", "about.impactDesc": "प्रतिबद्धता",
    "about.leadership": "नेतृत्व", "about.leadershipDesc": "टीम",
    "about.partners": "पार्टनर", "about.partnersDesc": "नेटवर्क",
    "about.joinCta": "सामील?", "about.joinCtaDesc": "नोंदणी.", "about.joinBtn": "नोंदणी",
    "elev.elderlyCare": "ज्येष्ठ", "elev.patientHandling": "रुग्ण", "elev.physiotherapy": "फिझिओ",
  },

  te: {
    "nav.home": "హోమ్", "nav.about": "మా గురించి", "nav.services": "సేవలు", "nav.register": "నమోదు", "nav.profile": "నా ప్రొఫైల్", "nav.help": "సహాయం",
    "nav.login": "లాగిన్", "nav.book": "సేవ బుక్ చేయండి", "nav.settings": "సెట్టింగ్‌లు", "nav.darkMode": "డార్క్ మోడ్", "nav.language": "భాష",
    "hero.badge": "సహకార సేవల భవిష్యత్తు",
    "hero.title1": "ధృవీకరించబడిన కార్మికులు.", "hero.title2": "న్యాయమైన వేతనాలు. నాణ్యమైన సేవ.",
    "hero.desc": "GharPe మిమ్మల్ని సహకార-ధృవీకరించబడిన వృత్తిపరులతో కలుపుతుంది.",
    "hero.cta1": "సేవ బుక్ చేయండి", "hero.cta2": "కార్మికుడిగా చేరండి",
    "hero.trust1": "బహు-స్థాయి ధృవీకరణ", "hero.trust2": "బీమా-సపోర్ట్", "hero.trust3": "న్యాయమైన వేతనం",
    "marquee.verifiedWorkers": "ధృవీకరించబడిన సహకార కార్మికులు", "marquee.fairWages": "న్యాయమైన వేతనాలు",
    "marquee.insurance": "బీమా-సపోర్ట్ సేవలు", "marquee.trust": "సమాజ నమ్మకం",
    "marquee.pricing": "పారదర్శక ధరలు", "marquee.emergency": "24/7 అత్యవసర సహాయం",
    "marquee.owned": "సహకార యాజమాన్యం", "marquee.trained": "వృత్తిపరంగా శిక్షణ పొందిన",
    "marquee.idVerified": "ఐడీ ధృవీకరించబడింది", "marquee.background": "నేపథ్య తనిఖీ",
    "stats.workers": "ధృవీకరించబడిన కార్మికులు", "stats.societies": "సహకార సంస్థలు",
    "stats.services": "పూర్తయిన సేవలు", "stats.rating": "సగటు రేటింగ్",
    "categories.badge": "సేవలు", "categories.title": "జనాదరణ సేవా వర్గాలు",
    "categories.desc": "గృహ మరియు సంస్థాగత సేవల్లో ధృవీకరించబడిన వృత్తిపరులను బ్రౌజ్ చేయండి",
    "cat.electrician": "ఎలక్ట్రీషియన్", "cat.plumber": "ప్లంబర్", "cat.carpenter": "కార్పెంటర్",
    "cat.painter": "పెయింటర్", "cat.domestic": "గృహ సహాయం", "cat.caregiver": "సంరక్షకుడు",
    "cat.driver": "డ్రైవర్", "cat.gardener": "తోటగాడు", "cat.cleaner": "శుభ్రం చేసేవారు", "cat.technician": "టెక్నీషియన్",
    "why.badge": "GharPe ఎందుకు", "why.title": "మరొక గిగ్ యాప్ కాదు",
    "why.desc": "నమ్మకం, న్యాయం మరియు సమాజంపై నిర్మించిన సహకార వేదిక.",
    "why.verification.title": "బహు-స్థాయి ధృవీకరణ", "why.verification.desc": "ప్రతి కార్మికుడు సహకార ఫెడరేషన్ ద్వారా ధృవీకరించబడతారు.",
    "why.wages.title": "కార్మికులకు న్యాయమైన వేతనాలు", "why.wages.desc": "సహకార మోడల్ ఎక్కువ పారిశ్రామికం నిర్ధారిస్తుంది.",
    "why.insurance.title": "బీమా-సపోర్ట్ కార్మికులు", "why.insurance.desc": "అందరు నమోదైన కార్మికులు సహకార బీమాలో ఉన్నారు.",
    "why.pricing.title": "పారదర్శక ధరలు", "why.pricing.desc": "దాగిన ఛార్జీలు లేవు.",
    "why.local.title": "స్థానిక సహకార ఉనికి", "why.local.desc": "కార్మికులు మీ ప్రాంతం నుండి.",
    "why.community.title": "సమాజ-నడిపించే", "why.community.desc": "సహకార ఉద్యమం ద్వారా నిర్మించబడింది.",
    "how.badge": "ప్రక్రియ", "how.title": "ఇది ఎలా పనిచేస్తుంది", "how.desc": "నాలుగు సులభమైన దశల్లో",
    "how.search": "వెతకండి", "how.search.desc": "ధృవీకరించబడిన కార్మికుల జాబితాలో సేవను వెతకండి.",
    "how.book": "బుక్", "how.book.desc": "తేదీ, సమయం ఎంచుకోండి.",
    "how.worker": "కార్మికుడు వస్తారు", "how.worker.desc": "సహకార-ధృవీకరించబడిన వృత్తిపరుడు వస్తారు.",
    "how.pay": "చెల్లించండి", "how.pay.desc": "UPI, కార్డ్ లేదా నగదు ద్వారా.",
    "who.badge": "అందరి కోసం", "who.title": "మేము ఎవరికి సేవ అందిస్తాము",
    "who.desc": "గృహాలు, సంస్థలు లేదా నైపుణ్య కార్మికులు — GharPe మీ కోసం.",
    "who.households": "గృహాలు", "who.households.desc": "మరమ్మతుల నుండి శుభ్రపరచడం వరకు.",
    "who.institutions": "సంస్థలు", "who.institutions.desc": "కార్యాలయాలు, పాఠశాలలు, ఆసుపత్రులు.",
    "who.elderly": "వృద్ధులు & రోగులు", "who.elderly.desc": "ధృవీకరించబడిన సంరక్షకులు.",
    "who.workers": "సహకార కార్మికులు", "who.workers.desc": "సహకార ప్రయోజనాలు కొనసాగిస్తూ.",
    "impact.badge": "ప్రభావం", "impact.title": "ముఖ్యమైన సంఖ్యలు", "impact.desc": "వాస్తవ ప్రభావం",
    "coop.badge": "సహకార మోడల్", "coop.title": "సహకార గొలుసు ఎలా పనిచేస్తుంది", "coop.desc": "సంఘటిత వ్యవస్థ",
    "coop.federations": "ఫెడరేషన్లు", "coop.federations.desc": "ప్రమాణాలు నిర్ణయిస్తాయి",
    "coop.societies": "సంఘాలు", "coop.societies.desc": "స్థానిక కార్మికుల నిర్వహణ",
    "coop.verified": "ధృవీకరించబడిన కార్మికులు", "coop.verified.desc": "బహు-స్థాయి ధృవీకరణ",
    "coop.you": "మీరు", "coop.you.desc": "ఆత్మవిశ్వాసంతో బుక్ చేయండి",
    "testimonials.badge": "సాక్ష్యాలు", "testimonials.title": "మా సమాజం చెప్పేది", "testimonials.desc": "నిజమైన కథలు",
    "emergency.title": "అత్యవసర సహాయం కావాలా?", "emergency.desc": "అత్యవసర సేవను బుక్ చేయండి.",
    "emergency.cta": "అత్యవసర సేవ బుక్ చేయండి",
    "cta.title": "ప్రారంభించడానికి సిద్ధంగా ఉన్నారా?", "cta.desc": "GharPe మీ కోసం ఇక్కడ ఉంది.",
    "cta.noSignup": "సైన్ అప్ ఫీజు లేదు", "cta.cancel": "ఎప్పుడైనా రద్దు", "cta.support": "24/7 మద్దతు",
    "footer.desc": "సహకార-యాజమాన్య మార్కెట్.", "footer.quickLinks": "లింక్‌లు", "footer.contact": "సంప్రదించండి",
    "footer.tollFree": "టోల్ ఫ్రీ, 9-8", "footer.response": "24 గంటల్లో",
    "footer.address": "ఘర్‌పే ప్రధాన కార్యాలయం", "footer.city": "కోల్‌కతా, పశ్చిమ బెంగాల్",
    "footer.newsletter": "అనుసంధానంగా ఉండండి", "footer.newsletterDesc": "అప్‌డేట్‌లు పొందండి.",
    "footer.emailPlaceholder": "ఇమెయిల్", "footer.subscribe": "సబ్స్క్రైబ్",
    "footer.toggleHint": "డార్క్ మోడ్ టాగిల్ చేయండి", "footer.privacy": "గోప్యతా విధానం",
    "footer.terms": "సేవా నిబంధనలు", "footer.bylaws": "సహకార నియమాలు",
    "services.title": "ధృవీకరించబడిన కార్మికుడిని కనుగొనండి", "services.desc": "మీ అన్ని అవసరాల కోసం.",
    "services.searchPlaceholder": "వెతకండి...", "services.emergencyOnly": "అత్యవసరం మాత్రమే",
    "services.emergencyMode": "అత్యవసర మోడ్", "services.clear": "క్లియర్",
    "services.workersFound": "కార్మికులు", "services.noResults": "లేరు", "services.noResultsDesc": "ఫిల్టర్ మార్చండి",
    "services.bookNow": "ఇప్పుడే బుక్", "services.viewProfile": "ప్రొఫైల్", "services.verified": "ధృవీకరించబడింది",
    "services.starting": "ప్రారంభం", "services.back": "వెనుకకు",
    "services.skills": "నైపుణ్యాలు", "services.certifications": "సర్టిఫికేషన్లు", "services.availability": "లభ్యత", "services.reviews": "సమీక్షలు",
    "booking.title": "బుక్", "booking.date": "తేదీ", "booking.time": "సమయం", "booking.selectTime": "సమయం ఎంచుకోండి",
    "booking.address": "చిరునామా", "booking.addressPlaceholder": "చిరునామా",
    "booking.description": "వివరణ", "booking.descPlaceholder": "ఏమి చేయాలి...",
    "booking.fee": "ఫీజు", "booking.platformFee": "ప్లాట్‌ఫార్మ్", "booking.total": "మొత్తం",
    "booking.payment": "చెల్లింపు", "booking.confirm": "బుకింగ్ నిర్ధారించండి", "booking.confirmed": "బుకింగ్ నిర్ధారించబడింది!",
    "booking.confirmedMsg": "త్వరలో సంప్రదించారు.", "booking.done": "అయిపోయింది", "booking.processing": "ప్రాసెస్ అవుతోంది...",
    "register.title": "చేరండి", "register.desc": "నమోదు చేయండి",
    "register.customer": "కస్టమర్ నమోదు", "register.worker": "కార్మికుడు నమోదు", "register.society": "సంఘం నమోదు",
    "register.fullName": "పూర్తి పేరు", "register.phone": "ఫోన్", "register.email": "ఇమెయిల్",
    "register.address": "చిరునామా", "register.useLocation": "స్థానం", "register.language": "భాష",
    "register.password": "పాస్‌వర్డ్", "register.confirmPassword": "నిర్ధారణ",
    "register.terms": "అంగీకరిస్తున్నాను", "register.termsLink": "నిబంధనలు", "register.privacyLink": "గోప్యత",
    "register.createAccount": "ఖాతా సృష్టించండి", "register.personalDetails": "వ్యక్తిగత వివరాలు",
    "register.coopAffiliation": "సహకార అనుబంధం", "register.selectCoop": "ఎంచుకోండి",
    "register.membershipId": "సభ్యత్వ ID", "register.skillProfiling": "నైపుణ్య ప్రొఫైలింగ్",
    "register.serviceCategories": "సేవా వర్గాలు", "register.yearsExp": "అనుభవం",
    "register.certUpload": "సర్టిఫికేట్లు", "register.serviceArea": "సేవా ప్రాంతం",
    "register.availableDays": "లభ్యమైన రోజులు", "register.paymentDetails": "చెల్లింపు వివరాలు",
    "register.bankName": "బ్యాంక్", "register.ifsc": "IFSC", "register.accountNumber": "ఖాతా",
    "register.insurance": "బీమాలో చేరండి", "register.insuranceDesc": "యాదృచ్ఛిక బీమా, ఆరోగ్యం.",
    "register.submitApp": "దరఖాస్తు", "register.societyName": "సంఘం పేరు",
    "register.regNumber": "నమోదు నంబర్", "register.region": "ప్రాంతం",
    "register.contactPerson": "సంప్రదింపు", "register.memberCount": "సభ్యులు",
    "register.registerSociety": "నమోదు",
    "register.success.customer": "ఖాతా!", "register.success.customerDesc": "స్వాగతం.",
    "register.success.worker": "దరఖాస్తు!", "register.success.workerDesc": "ధృవీకరణలో.",
    "register.success.society": "నమోదు!", "register.success.societyDesc": "ధృవీకరణ.",
    "help.title": "సహాయం", "help.title2": "& మద్దతు", "help.desc": "సమాధానాలు కనుగొనండి",
    "help.emergency": "అత్యవసరం", "help.emergencyDesc": "కాల్ చేయండి.", "help.callEmergency": "1800-123-4567",
    "help.contactTitle": "సంప్రదింపులు", "help.callSupport": "కాల్", "help.callSupportDesc": "9-8",
    "help.emailSupport": "ఇమెయిల్", "help.emailSupportDesc": "24 గంటలు", "help.liveChat": "చాట్", "help.liveChatDesc": "చాట్ చేయండి", "help.startChat": "ప్రారంభం",
    "help.complaint": "ఫిర్యాదు", "help.complaintDesc": "నివేదించండి", "help.fileComplaint": "దాఖలు",
    "help.faqTitle": "తరచుగా అడిగే ప్రశ్నలు", "help.noResults": "లేదు", "help.noResultsDesc": "మార్చండి",
    "help.searchPlaceholder": "వెతకండి...", "help.welfareTitle": "కార్మిక సంక్షేమం", "help.welfareDesc": "బీమా-సపోర్ట్.",
    "help.learnMore": "మరిన్ని", "help.chatTitle": "GharPe సహాయం", "help.chatPlaceholder": "సందేశం...",
    "about.title": "GharPe గురించి", "about.desc": "సహకార-యాజమాన్య వేదిక.",
    "about.mission": "మా లక్ష్యం", "about.missionDesc": "న్యాయమైన మార్కెట్ సృష్టించడం.",
    "about.vision": "మా దృష్టి", "about.visionDesc": "కార్మికుల సాధికారత.",
    "about.storyBadge": "మా కథ", "about.storyTitle": "సహకారం నుండి డిజిటల్",
    "about.model": "సహకార మోడల్", "about.modelDesc": "సంఘటిత వ్యవస్థ",
    "about.impact": "ప్రభావం", "about.impactDesc": "నిబద్ధత",
    "about.leadership": "నాయకత్వం", "about.leadershipDesc": "బృందం",
    "about.partners": "భాగస్వాములు", "about.partnersDesc": "నెట్‌వర్క్",
    "about.joinCta": "చేరాలా?", "about.joinCtaDesc": "నమోదు చేయండి.", "about.joinBtn": "నమోదు",
    "elev.elderlyCare": "వృద్ధి సంరక్షణ", "elev.patientHandling": "రోగి సంరక్షణ", "elev.physiotherapy": "ఫిజియోథెరపీ",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>("en");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem("gharpe-lang") as LangCode | null;
    if (stored && translations[stored]) setLangState(stored);
    setMounted(true);
  }, []);

  useEffect(() => {
    if (mounted) {
      localStorage.setItem("gharpe-lang", lang);
      document.documentElement.lang = lang === "en" ? "en" : lang === "hi" ? "hi" : lang === "bn" ? "bn" : lang === "mr" ? "mr" : "te";
    }
  }, [lang, mounted]);

  const setLang = useCallback((l: LangCode) => setLangState(l), []);

  const t = useCallback((key: string): string => {
    return translations[lang]?.[key] ?? translations.en[key] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within a LanguageProvider");
  return ctx;
}